### ISSUE TITLE
8.2.0 regression in /forms/pdfengines/convert

### ISSUE THREAD

**Issue by stumpylog** [gotenberg/gotenberg#820]
Given the sample test below, this will pass against Gotenberg 8.0.2, but will fail against 8.2.0, which returns a 501 Not Implemented.

The container logs:
```
error   api     convert PDF: convert PDF to '{PdfA:PDF/A-2b PdfUa:false}' with multi PDF engines: convert PDF to '{PdfA:PDF/A-2b PdfUa:false}' with LibreOffice: convert to PDF: unix process error: wait for unix process: exit status 5; convert PDF to '{PdfA:PDF/A-2b PdfUa:false}' with PDFcpu: method not supported; convert PDF to '{PdfA:PDF/A-2b PdfUa:false}' with PDFtk: method not supported; convert PDF to '{PdfA:PDF/A-2b PdfUa:false}' with QPDF: method not supported      {"trace": "e00f7493-983a-42d2-8c5f-217a2a4cb1ee", "remote_ip": "127.0.0.1", "host": "localhost:3000", "uri": "/forms/pdfengines/convert", "method": "POST", "path": "/forms/pdfengines/convert", "referer": "", "user_agent": "python-httpx/0.27.0", "status": 501, "latency": 2199195819, "latency_human": "2.199195819s", "bytes_in": 417027, "bytes_out": 15}
```

Sample test:
```python
with httpx.Client(base_url="http://localhost:3000") as client:
    resp = client.post(
        "/forms/pdfengines/convert",
        data={"pdfa": "PDF/A-2b"},
        files={
            "sample-1.pdf": ("sample-1.pdf", (SAMPLE_DIR / "sample1.pdf").open("rb"), "application/pdf"),
            "sample-2.pdf": ("sample-2.pdf", (SAMPLE_DIR / "sample2.pdf").open("rb"), "application/pdf"),
        },
    )
    assert resp.status_code == httpx.codes.OK
    assert "Content-Type" in resp.headers
    assert resp.headers["Content-Type"] == "application/zip"
```

**Comment by stumpylog** [comment]
8.1.0 returns an HTTP 500 server error, logging:

```
error   api     convert PDF: convert PDF to '{PdfA:PDF/A-2b PdfUa:false}' with multi PDF engines: convert PDF to '{PdfA:PDF/A-2b PdfUa:false}' with LibreOffice: convert to PDF: unix process error: wait for unix process: exit status 5; convert PDF to '{PdfA:PDF/A-2b PdfUa:false}' with PDFcpu: method not supported; convert PDF to '{PdfA:PDF/A-2b PdfUa:false}' with PDFtk: method not supported; convert PDF to '{PdfA:PDF/A-2b PdfUa:false}' with QPDF: method not supported      {"trace": "5fca587c-adca-40c8-aa62-7b2176326f2e", "remote_ip": "127.0.0.1", "host": "localhost:3000", "uri": "/forms/pdfengines/convert", "method": "POST", "path": "/forms/pdfengines/convert", "referer": "", "user_agent": "python-httpx/0.27.0", "status": 500, "latency": 2029178192, "latency_human": "2.029178192s", "bytes_in": 417027, "bytes_out": 21}
```

**Comment by stumpylog** [comment]
8.0.3 is also fine

**Comment by stumpylog** [comment]
Sending a single file is fine on 8.2.0, so perhaps the problem lies in the returning of a zip file or its creation

**Comment by gulien** [comment]
Confirmed 👍

**Comment by stumpylog** [comment]
Let me know if you have a build you'd like me to test against.  I think my client's test suite is decently comprehensive over the API and its options.

**Comment by gulien** [comment]
Thanks, but I know exactly what’s wrong; it’s a new change I’ve introduced recently 😅

**Comment by gulien** [comment]
Fixed in https://github.com/gotenberg/gotenberg/commit/0f8bbead66a00ac5cff953b8a87ac43c13a1bc1e.

**Comment by stumpylog** [comment]
This made it into 8.2.1, correct?  The error code has changed (500 now), but the test still fails against the latest 8.2.1 image

Maybe related is #835

**Comment by gulien** [comment]
Yep, the wrong error code has been fixed but now there ls another issue 👌

**Comment by gulien** [comment]
@stumpylog Would you mind sharing your functional tests? My unit tests are definitely not enough to catch everything 😅

**Comment by stumpylog** [comment]
The branch where I'm testing out v8 support is here: https://github.com/stumpylog/gotenberg-client/tree/feature/breaking_v8_only
